### ISSUE TITLE
2 - Zapętlający się rosjanin

### ISSUE THREAD

**Issue by Awojda** [FurtakM/SoSAm#369]
Poziom trudności: średni
Kroki:
W sumie to ciężko określić, po przejęciu drugiej bazy , ustawieniu przenoszenia skrzynek z pierwszej wyprowadziłem rosjanina na spacer. Ten w momencie gdy miał wchodzić do środka zmienił kolor na mój, podejmował cały czas skrzynkę, kładł ją do składu i tak w kółko. Interfejs zniknął, całość wyglądała jak cutscenka.

**Comment by FurtakM** [comment]
Poprawka wrzucona. Do przetestowania.

#371

**Comment by Awojda** [comment]
Błąd naprawiony
