### ISSUE TITLE
3 - random crash

### ISSUE THREAD

**Issue by Awojda** [FurtakM/SoSAm#372]
Error wyskakuje po wysłaniu Franka na zwiad i (w moim wypadku) wybudowaniu laboratorium
General Info
------------
Application            : Owarogl
Version                : 2.0.7.188_OGL

ModName                : AmRemake
ModDir                 : AmR
ModVer                 : 0.1 (0.1)

ErrorType              : Unknown
ErrorText              : procedure destroy_unit(obj:POWUnit; CreateDeadUnit: Boolean = True; Force: Boolean = False); Access violation at address 00665D56 in module 'OwarOGL.exe'. Read of address 00000017

Exception              : None
Stack                  : 006A2B63
Stack                  : 006A3F17
Stack                  : 75AB6359
Stack                  : 77A17B74
Stack                  : 77A17B44

Params                 : 
ParamCount             : 0

Game Info
---------
Multiplayer            : False
Multi.GameState        : NotConnected
Multi.ChatConnLost     : False
Multi.IAMServer        : False
Multi.Joined           : False
Multi.Loaded           : False
Multi.MapVersion       : 0
Multi.OffLine          : True
Multi.OnLine           : False
Multi.ServerLost       : False
Multi.StatusText       : 
MultiDef.MapName       : 

mission_number         : 3
mission_campaign       : 1
camp_names[mission_campaign] : Am
mission_names[mission_number] : 03 
game_difficulty        : 1
ingame_video           : False
stop_talking           : False
stop_action            : False
end_of_mission         : 0
end_the_mission_allowed : False
dialogue_skipped       : False
last_title_ident       : -1
last_title_unit        : 130
last_title_radio       : False
last_title             : Te skrzynie się przydadzą.

lastSail               : 17370
tick                   : 14058

Random Stuff
------------
GodMode                : False
DeveloperMode          : False
ModCBMode              : False
OfficialMod            : False
InterfSide             : 1
MultiCore              : True

Windows Info
------------
Product                : Windows 10
Win32MajorVersion      : 10
Win32MinorVersion      : 0
BuildNumber            : 9200
ServicePack            : 
ServicePackMajor       : 0
ServicePackMinor       : 0

Physical Memory        : 16333MB
CPU Name               : AMD Ryzen 5 1600X Six-Core Processor           
CPU Clock              : 3593Mhz
Current CPU Clock      : 3600Mhz

**Comment by FurtakM** [comment]
Błąd silnika gry, już zgłoszony.

**Comment by FurtakM** [comment]
https://owsupport.com/files/public/SGUI/SGUI_WIP_PATCH-2019-09-26.rar

Podobno ta łatka naprawia powyższy błąd. Do sprawdzenia.

**Comment by Awojda** [comment]
Łatka poprawia błąd, wszystko jest okej
