### ISSUE TITLE
11 - czasami respawnuje się tylko jedna ciężarówka z artefaktem

### ISSUE THREAD

**Issue by Awojda** [FurtakM/SoSAm#375]

**Comment by FurtakM** [comment]
Tu chyba chodzi o 1 misję przymierza? Liczba artefaktów zależy od tego czy gracz przejął artefakt w 11 misji.

**Comment by Awojda** [comment]
fakt, moje niedopatrzenie jeżeli chodzi o numer misji. Ciężarówka jest zebrana, błąd występuje w momencie odpalania misji "od początku" z poziomu menu kontekstowego
