### ISSUE TITLE
01_cont

### ISSUE THREAD

**Issue by JakesFromBB** [FurtakM/SoSAm#381]
Przy szybkim wznowieniu misji, Bobby Brandon ginie. Jak się rozpocznie misję od nowa, to nic takiego nie ma miejsca.

![image](https://user-images.githubusercontent.com/12738407/67156615-30d13c80-f321-11e9-833e-367fd8fcbf83.png)

**Comment by JakesFromBB** [comment]
Po szybkim wznowieniu Cyrus nie leży w krzakach, tylko stoi obok krzaków.

**Comment by FurtakM** [comment]
Naprawione.
#383
