### ISSUE TITLE
02

### ISSUE THREAD

**Issue by JakesFromBB** [FurtakM/SoSAm#382]
Gdy przejmiemy obydwa składy a nie zabijemy wszystkich rusków z bazy lewej, to nie ma dialogu z Powellem - mimo to przyjeżdża ekipa do Nataszy i misja idzie dalej.

To samo, gdy przejmiemy tylko lewy skład, to dzieje się to co wyżej. Bez dialogu gra "idzie dalej".

**Comment by FurtakM** [comment]
Naprawione.
#383
