### ISSUE TITLE
06_cont - przybycie Denisa

### ISSUE THREAD

**Issue by FurtakM** [FurtakM/SoSAm#388]
![Obraz](https://i.gyazo.com/33230ca032d296005608256d3e83fc85.png)

Denis powinien pojawiać się możliwe jak najbliżej bazy.

**Comment by FurtakM** [comment]
Denis pojawia się w tym samym miejscu w którym pojawiają się jednostki na początku misji - jest to logiczne bo tam jest najbliższy punkt z bazy Delta. Poza tym, skąd Denis miałby wiedzieć gdzie dokładnie jest baza :question:

**Comment by ralf321** [comment]
Ta tylko jeśli akurat jest atak ruskich z automatu ginie

**Comment by FurtakM** [comment]
Dodałem warunek że Denis pojawia się tylko gdy w okolicy nie ma ruskich.
