### ISSUE TITLE
Kurt rozmawia z nowo przybyłym xD 

### ISSUE THREAD

**Issue by ralf321** [FurtakM/SoSAm#389]
![image](https://user-images.githubusercontent.com/59265541/71490898-bf849d00-282d-11ea-93ca-b6c9dafca356.png)

**Comment by ralf321** [comment]
![image](https://user-images.githubusercontent.com/59265541/71490967-33bf4080-282e-11ea-9ff8-6e38a03c4f67.png)
![image](https://user-images.githubusercontent.com/59265541/71490992-4f2a4b80-282e-11ea-89c4-959d5e170570.png)

A mógł uciekać a nie przychodzić do mojej bazy

**Comment by FurtakM** [comment]
Powinno być ok.
