### ISSUE TITLE
08 - Ruscy pokonani przed 1 atakiem 

### ISSUE THREAD

**Issue by ralf321** [FurtakM/SoSAm#393]
![image](https://user-images.githubusercontent.com/59265541/71560689-7a4eae00-2a6d-11ea-9d3d-9947454dc57a.png)
Straty minimalnej 1 człowiek i 1 pojazd chyba. 
Jmm nie zdążył nawet wrócić :P 
Bo po co on komu :D

**Comment by ralf321** [comment]
![image](https://user-images.githubusercontent.com/59265541/71560708-c0a40d00-2a6d-11ea-8d84-c459d7b007e6.png)
![image](https://user-images.githubusercontent.com/59265541/71560713-c8fc4800-2a6d-11ea-80bc-9d1dfb600854.png)
![image](https://user-images.githubusercontent.com/59265541/71560727-dd404500-2a6d-11ea-80cc-2241c0064cd0.png)
![image](https://user-images.githubusercontent.com/59265541/71560742-1a0c3c00-2a6e-11ea-99f4-39541aa0d56a.png)
![image](https://user-images.githubusercontent.com/59265541/71560762-37d9a100-2a6e-11ea-92db-c600d790522e.png)
![image](https://user-images.githubusercontent.com/59265541/71560785-753e2e80-2a6e-11ea-92aa-c1afa222b7a5.png)

A jednak w 09 by się przydał :(

**Comment by FurtakM** [comment]
Teraz powinno być ok.

**Comment by Mieciu125** [comment]
jeżeli zniszczysz baze przed przybyciem johna to stracisz wszystkich ludzi (+johna) w przyszłych misjach
