### ISSUE TITLE
08 - Ruscy nie mają broni na wieżyczkach why? 

### ISSUE THREAD

**Issue by ralf321** [FurtakM/SoSAm#394]
![image](https://user-images.githubusercontent.com/59265541/71560898-d0bcec00-2a6f-11ea-80c3-14429973878d.png)

I wszystko jasne zablokowali się i nie zbudowali rozwoju dział 

![image](https://user-images.githubusercontent.com/59265541/71560928-12e62d80-2a70-11ea-9bad-0ed5ef43c242.png)

Myślę ze miło by było zobaczyć też odliczanie kiedy dostaniemy posiłki z Alfy.

**Comment by Mieciu125** [comment]
w tej misji jest system rozbudowy = rosjanie dopiero budują budynki i rozbudowy do fabryki na co się przekłada budowa broni na wieżyczki w określonym czasie
