### ISSUE TITLE
09 - 303 skrzynki ale jak? 

### ISSUE THREAD

**Issue by ralf321** [FurtakM/SoSAm#396]
![image](https://user-images.githubusercontent.com/59265541/71561258-868a3980-2a74-11ea-8a77-85e451075934.png)

 Myślę że dostarczyli zamiast 200 to 193 złodzieje jedne ;/ Do sprawdzenia

**Comment by FurtakM** [comment]
`AddResourceType(GetBase(terminal), mat_cans, 200);`

Nie ma więc opcji aby dostarczyli tylko 193 skrzynek.
