### ISSUE TITLE
10 - Kim jest ten człek i gdzie on się chowa?

### ISSUE THREAD

**Issue by ralf321** [FurtakM/SoSAm#398]
![image](https://user-images.githubusercontent.com/59265541/71564448-b9e2bd80-2aa0-11ea-81aa-91cbe5bcd333.png)

Tak nie posiadam w swojej drużynie aktualnie żadnego Williams'a 
I tak sprawdzałem 3 razy.

**Comment by ralf321** [comment]
Oki to fachowiec od min :D Tylko dlaczego wysadza moich ludzi ehhh nikomu nie wolno ufać xD 

![image](https://user-images.githubusercontent.com/59265541/71564487-3aa1b980-2aa1-11ea-92fa-e1bc01a2288f.png)

**Comment by FurtakM** [comment]
Nie za bardzo czaje o co chodzi.

**Comment by ralf321** [comment]
Widzisz gościa któremu rosną umiejętności jak wysadza moich ludzi minami w arabskiej bazie dlaczego mam komunikaty o wzroście jego umiejętności?

**Comment by Mieciu125** [comment]
mamy z serpentem ten problem od kilku dni i nie możemy wyczaić o co z tym typem chodzi

**Comment by FurtakM** [comment]
Do sprawdzenia czy ten błąd występuje na obecnej wersji.
