### ISSUE TITLE
10 - Po co pyta czy chce kontynuować misję jeśli i tak mi ją zakończy? 

### ISSUE THREAD

**Issue by ralf321** [FurtakM/SoSAm#399]
![image](https://user-images.githubusercontent.com/59265541/71564816-09c48300-2aa7-11ea-90a1-e472d9b2c3d9.png)

Sytuacja kiedy wszystkie cele główne i poboczne są osiągnięte a ostatnim celem jest badanie syberytu i przy skończonym badaniu daje komunikat czy kontynuować.

**Comment by FurtakM** [comment]
Naprawione. Teraz żeby zakończyć misję trzeba potwierdzić zakończenie misji.
