### ISSUE TITLE
11 - A Cornell to gdzie jest? 

### ISSUE THREAD

**Issue by ralf321** [FurtakM/SoSAm#401]
Nie mam do wyboru Cornella wredny czarnuch poszedł na L4? 
[Domyślny1.zip](https://github.com/FurtakM/SoSAm/files/4010014/Domyslny1.zip)

**Comment by Mieciu125** [comment]
Cornell się buguje i trzeba jego kod napisać od nowa

**Comment by FurtakM** [comment]
Do sprawdzenia czy Cornell pojawia się w 11 misji w obecnej wersji (wymagane przejście misji 10 na tej wersji).
